function [abRawFolder, acKofikoFile, acSessionInfo] = fnIsRawFolder(acAllFolders, hAxes)
iNumFolders = length(acAllFolders);
abRawFolder = zeros(1,iNumFolders) > 0;

acKofikoFile = cell(1,iNumFolders);
acSessionInfo = cell(1,iNumFolders);
iSameDaySession=1;
for iFolderIter=1:iNumFolders
    % Conditions for a folder to be a "RAW" folder
    % 1. it has a MAT file that was generated by Kofiko
    
    fnSetWaitbar(hAxes, iFolderIter/iNumFolders);
    

    astrctMatFiles = dir(fullfile(acAllFolders{iFolderIter},'*.mat'));
    for k=1:length(astrctMatFiles)
        [bValid,strctInfo] = fnGetSessionInformation(fullfile( acAllFolders{iFolderIter},astrctMatFiles(k).name));
        if bValid && ~isempty(strctInfo)
            abRawFolder(iFolderIter) = true;
            acKofikoFile{iFolderIter}{iSameDaySession} = fullfile( acAllFolders{iFolderIter},astrctMatFiles(k).name);
            acSessionInfo{iFolderIter}{iSameDaySession} = strctInfo;
            iSameDaySession=iSameDaySession+1;
        end;
    end
    

end

return;
